export enum MetricCategory {
  PERFORMANCE = 'PERFORMANCE',
  BUSINESS = 'BUSINESS',
  USER_ACTIVITY = 'USER_ACTIVITY',
  SYSTEM = 'SYSTEM',
  ERROR = 'ERROR',
  SALES = 'SALES',
  OPERATIONAL = 'OPERATIONAL',
  CUSTOMER = 'CUSTOMER',
  FINANCIAL = 'FINANCIAL'
}

export enum AggregationPeriod {
  HOURLY = 'HOURLY',
  DAILY = 'DAILY',
  WEEKLY = 'WEEKLY',
  MONTHLY = 'MONTHLY',
  QUARTERLY = 'QUARTERLY',
  YEARLY = 'YEARLY'
}

export enum ReportFormat {
  JSON = 'JSON',
  CSV = 'CSV',
  PDF = 'PDF',
  EXCEL = 'EXCEL'
}

export enum ReportExecutionStatus {
  PENDING = 'PENDING',
  RUNNING = 'RUNNING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED'
}