version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - VITE_STELLAR_NETWORK=${STELLAR_NETWORK}
      - VITE_HORIZON_URL=${HORIZON_URL}
      - VITE_API_BASE_URL_BACKEND=${API_BASE_URL_BACKEND}
      - VITE_API_BASE_URL_FRONTEND=${API_BASE_URL_FRONTEND}
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./apps/backend:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - STELLAR_NETWORK=${STELLAR_NETWORK}
      - HORIZON_URL=${HORIZON_URL}
      - API_BASE_URL_BACKEND=${API_BASE_URL_BACKEND}
      - API_BASE_URL_FRONTEND=${API_BASE_URL_FRONTEND} 
